# Generated by Django 2.1.5 on 2020-11-16 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catID', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('description', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('advAmtPaid', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(choices=[('PARTY HALL', 'PARTY HALL'), ('SWIMMING POOL', 'SWIMMING POOL'), ('KIDS PLAYING AREA', 'KIDS PLAYING AREA')], max_length=50)),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED'), ('NEW', 'NEW')], max_length=50)),
                ('reason', models.CharField(blank=True, max_length=200, null=True)),
                ('participantCount', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifiedBy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('pickupDateTime', models.DateTimeField(blank=True, max_length=100, null=True)),
                ('pickupPerson', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('standard', 'STANDARD'), ('urgent', 'URGENT')], default='standard', max_length=50)),
                ('status', models.CharField(blank=True, choices=[('new', 'NEW'), ('in-progress', 'IN-PROGRESS'), ('completed', 'COMPLETED')], max_length=100, null=True)),
                ('accessInstructions', models.CharField(blank=True, max_length=200, null=True)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('perToEnter', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='mt.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('FEMALE', 'FEMALE'), ('MALE', 'MALE'), ('OTHERS', 'OTHERS')], max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('dob', models.DateField(blank=True, max_length=100, null=True)),
                ('vehNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Primary', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('moveInDate', models.DateField(blank=True, max_length=100, null=True)),
                ('moveOutDate', models.DateField(blank=True, max_length=100, null=True)),
                ('rent', models.PositiveIntegerField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID', models.PositiveIntegerField()),
                ('aptNo', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='residentdetail',
            name='unitID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='mt.UnitDetail'),
        ),
        migrations.AddField(
            model_name='residentdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requestdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='mt.ResidentDetail'),
        ),
        migrations.AddField(
            model_name='packagedetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='mt.ResidentDetail'),
        ),
        migrations.AddField(
            model_name='eventsdetail',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='mt.ResidentDetail'),
        ),
    ]
