# Generated by Django 3.0.2 on 2020-03-19 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catID', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitID', models.PositiveIntegerField()),
                ('aptNo', models.PositiveIntegerField()),
                ('street', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField(max_length=100)),
                ('vehNumber', models.CharField(blank=True, max_length=100)),
                ('is_Primary', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=200)),
                ('phone_number', models.PositiveIntegerField()),
                ('moveInDate', models.DateField(max_length=100)),
                ('moveOutDate', models.DateField(max_length=100)),
                ('rent', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('unitID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='mt.UnitDetail')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('standard', 'STANDARD'), ('urgent', 'URGENT')], default='standard', max_length=50)),
                ('status', models.CharField(choices=[('new', 'NEW'), ('in-progress', 'IN-PROGRESS'), ('completed', 'COMPLETED')], max_length=100)),
                ('accessInstructions', models.CharField(max_length=200)),
                ('perToEnter', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('modifiedBy', models.CharField(max_length=200)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='mt.Category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='mt.ResidentDetail')),
            ],
        ),
    ]
