# Generated by Django 3.0.3 on 2020-04-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0002_auto_20200422_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='mail_id',
            field=models.EmailField(max_length=254),
        ),
    ]
