# Generated by Django 3.0.3 on 2020-04-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mt', '0003_auto_20200424_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='mail_id',
            field=models.CharField(max_length=200),
        ),
    ]
